### ISSUE TITLE
А где .po файл?

### ISSUE THREAD

**Issue by firemdkfighter** [O-n-y/Oxygen-Not-Included---Russian-Translation#19]
А где .po файл?

**Comment by O-n-y** [comment]
Вам не нужен .po, используйте  	strings.pot

**Comment by firemdkfighter** [comment]
Откройте ваш strings.pot в poedit'е, там будет сбитая кодировка

**Comment by O-n-y** [comment]
UTF-8 и соответственно русский язык пока не поддерживается игрой, об этом писалось на форуме.
