### ISSUE TITLE
Отсутсвует перевод

### ISSUE THREAD

**Issue by Dipod** [O-n-y/Oxygen-Not-Included---Russian-Translation#46]
Отсутствует перевод у некоторых ресурсов в виджете справа вверху, где показывается количество наших ресурсов. Всплывающая подсказка тоже на английском.

**Comment by Dipod** [comment]
Слева вверху, где количество прошедших циклов, отстутствует перевод. Всплывающая подсказка тоже.

**Comment by Dipod** [comment]
Описание миксера микробов: ... используя наиболее общие компоненты. Мне кажется лучше будет: ... используя самые распространенные компоненты

**Comment by Dipod** [comment]
При выделении блока удобрения, справа в описании "Информация" в тексте вылез "style plant". Где то потеряли теги.

**Comment by Dipod** [comment]
Во вкладке Детали, при описании блоков отсутствует перевод у теплопроводности, точки плавления и теплоемкости.

**Comment by Dipod** [comment]
и у массы

**Comment by O-n-y** [comment]
Данные строки пока отсутствуют в файле локализации, Вы можете сообащать о найденных на трекер Klei, чтобы они добавили их - соответственно мы тогда сможем перевести на русский. 
Мы ограничены тем, что они включают в исходный файл для перевода.

Трекер клея:
http://forums.kleientertainment.com/klei-bug-tracker/oni-alpha/

Лучше всего это делать приводя скриншот.

В переводе сейчас переведены все строки, которые есть :)

**Comment by O-n-y** [comment]
"При выделении блока удобрения, справа в описании "Информация" в тексте вылез "style plant". Где то потеряли теги."
^ поправила, спасибо!
