### ISSUE TITLE
VITALS

### ISSUE THREAD

**Issue by pecypc** [O-n-y/Oxygen-Not-Included---Russian-Translation#48]
Меню VITALS(СТАТУС) не работает из-за перевода.

**Comment by O-n-y** [comment]
Конкретнее, что именно? 
То, что не отображается размер стресса, насколько я знаю, не из-за перевода (текста), а баг билда, если вы используете трансляцию (любую)

**Comment by pecypc** [comment]
Сытость тоже не отображается. Логично не переводить забагованные строки. Stress и Calories воспринимаются и без перевода.

**Comment by O-n-y** [comment]
там не в этом дело - они не будут работать, если в принципе есть перевод.

**Comment by pecypc** [comment]
Я же предложил не переводить.
17 Апр 2017 г. 4:18 пользователь "O-n-y" <notifications@github.com> написал:

**Comment by O-n-y** [comment]
Еще раз повторю, не влияет переведена ли данная строка или нет.
Влияет используете ли Вы локализацию или нет

**Comment by pecypc** [comment]
Я использую локализацию, убрал перевод, меню работает.

9 Май 2017 г. 20:52 пользователь "O-n-y" <notifications@github.com> написал:
