### ISSUE TITLE
Словарь

### ISSUE THREAD

**Issue by AirShark** [O-n-y/Oxygen-Not-Included---Russian-Translation#55]
Нужен более расширенный словарь, для тех же растений, порой встречаются разные названия.
Например Muckroot в одной строке переведен как "Гнойкорень" в другой уже "Гнилькорень"

Update:
Pincha Peppernut где-то как Орех (в одной строке вроде встретил) переводиться где-то как Пинча

Наверное все собрал с файла, пока не знаю что еще добавить

Meal Lice - Мукоеды
Mush bar - Мшистый батончик
Sleet Wheat - Морозная пшеница
Peppernut - Перечный орех
Pincha Peppernut - Перечный орех - Пинча перечная
Bristle Berry - Щетинистая ягодка
Stuffed Berry - Фаршированная ягодка
Thimble Reed - Прядун
Mealwood - Мучное Дерево
Wheezewort - Хладнодых - хладодых
Palmera Tree - Дерево Пальмера
Bristle Blossom - Щитовик Цветущий
Bristle Briar - Шиповник
Swamp Lily - Болотной Лилии
Muckroot - Гнилькорень - гнойкорень
Gristle Berry - Хрустящая Ягодка

Frost Bun - Ледяная булочка
Liceloaf - Батончик из мукоедов

**Comment by O-n-y** [comment]
Гнилькорень - поправила (это корректно название).
Пинча перечная - должна быть везде таковой, однако есть отдельный предмет - Перечный орех
Я добавила в ридми новые слова.
