### ISSUE TITLE
Ошибка в переводе 

### ISSUE THREAD

**Issue by Skvizz** [O-n-y/Oxygen-Not-Included---Russian-Translation#64]
Здравствуй. Нашел ошибку в переводе, а именно описание Уплотненного провода. Cannot be run through Tile переведено как "Может быть проложен через блоки..."

**Comment by O-n-y** [comment]
Это ошибка не перевода, а оригинального описания:
`msgid "Carries more <style=\"power\">Wattage</style> than regular Electrical Wire without overloading.\n\nCan be run through Tile."
msgstr "Пропускает больше <style=\"power\">Электричества</style>, чем обычные провода, без перегрузки.\n\nМожет быть проложен через блоки пола и стен."
`

Но я исправлю в русской версии, т.к. очевидно, что он не может быть проложен через них в текущей весрии
