### ISSUE TITLE
Need some checks & fixes

### ISSUE THREAD

**Issue by RetroGameIntros** [O-n-y/Oxygen-Not-Included---Russian-Translation#75]
Обнаружено без перевода и опечатки:

1) Атмосферный датчик и Термо-датчик - слово "**Activate if:**" не переведено.
![bandicam 2017-05-28 00-09-21-400](https://cloud.githubusercontent.com/assets/28905475/26524398/294cefc0-433a-11e7-8de2-9da721d47e70.jpg)
![bandicam 2017-05-28 00-09-24-737](https://cloud.githubusercontent.com/assets/28905475/26524397/294cbe4c-433a-11e7-8893-650433aaf11d.jpg)

2) Газовый фильтр - Статус "**Номинальный"** (опечатка?)
![bandicam 2017-05-28 00-09-03-083](https://cloud.githubusercontent.com/assets/28905475/26524404/4795ca88-433a-11e7-9686-571961b2f32b.jpg)

3) Пинча перечная - при наведении на "Холодное окружение" - **This creature cannot retain enough heat to stay warm in this area. It prefers temperatures between 35 С and 85 C** ; При наведении на Задыхается - **This plant has stopped growing because one of its basic requirements has been not met Unmet Condition: {0}**
![bandicam 2017-05-28 00-08-31-960](https://cloud.githubusercontent.com/assets/28905475/26524433/e841c856-433a-11e7-8255-ab8092470a52.jpg)
![bandicam 2017-05-26 21-00-43-841](https://cloud.githubusercontent.com/assets/28905475/26524444/119a0e98-433b-11e7-9135-a8aaf22f03b6.jpg)

**Comment by dmtazetdinov** [comment]
1. Activate if - переведено, возможно данного текста пока вообще нет для перевода (нет переменной). Поэтому мы добавить его не можем.
2. Номинальный - статус Nominal. Вроде все правильно.
> Номинальный режим (продолжительный режим) — такой режим работы машин и оборудования, при котором они могут наиболее эффективно работать на протяжении неограниченного времени (более нескольких часов).
3. Перевод уже направлен, ждем апрува

**Comment by O-n-y** [comment]
Перевод полностью обновлен до билда AU-218116
