### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by dmtazetdinov** [O-n-y/Oxygen-Not-Included---Russian-Translation#93]
**Баг с переводом (у нас почему-то не работает, хотя переведен):**
Этот я уже исправил, было дублирование {0}, поэтому перевод не работал
![bug_translation_1](https://user-images.githubusercontent.com/28824032/27398476-83c59ab0-56c2-11e7-9c79-bbc71b1399e0.png)
Вот осталось разобраться с этими:
![bug_translation_2](https://user-images.githubusercontent.com/28824032/27398478-83c77e98-56c2-11e7-9627-d85607d9beef.png)
![bug_translation_3](https://user-images.githubusercontent.com/28824032/27398475-83c442e6-56c2-11e7-8609-b04591481d0c.png)
![bug_translation_6](https://user-images.githubusercontent.com/28824032/27398480-83deb02c-56c2-11e7-956d-b235923d5ab7.png)

**Баги из игры:**
Можешь завести кейсы?
![bug_translation_4](https://user-images.githubusercontent.com/28824032/27398477-83c5875a-56c2-11e7-8e7c-5c24b62e1e90.png)
![bug_translation_5](https://user-images.githubusercontent.com/28824032/27398474-83c3ea08-56c2-11e7-84ef-8c33d18e1774.png)
![bug_translation_7](https://user-images.githubusercontent.com/28824032/27398479-83dc4878-56c2-11e7-924d-6da575ba3bd2.png)
![bug1](https://user-images.githubusercontent.com/28824032/27398473-83c26494-56c2-11e7-8d42-0eaf8f57090c.png)

**Comment by O-n-y** [comment]
Отключите перевод (переключитесь на англ серсию)
Сделайте скриншот того же самого на англ версии
В трекере ONI,  добавьте англ скриншоты с описанием

**Comment by O-n-y** [comment]
я посмотрю еще по коду, я сейчас посмотрела, думаю, у них баг парсера

**Comment by O-n-y** [comment]
или прикрепите сюда англоязычные скриншоты
+ к кажому кусок из файла с текстом (чтобы связать скриншот с айди строки)

**Comment by O-n-y** [comment]
я создала тикет

**Comment by O-n-y** [comment]
наши правки локализации не нужны, это они должны пофиксить в коде.
